import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service | terribly made notes app" };

export default function TermsPage() {
  return (
    <div className="container" style={{ maxWidth: 720, lineHeight: 1.6, padding: "32px 20px" }}>
      <h1>Terms of Service</h1>
      <p><em>Last updated October 1, 2026</em></p>
      <p>
        These terms cover your use of notes.kobosh.com, a personal service run by one person. By using it you
        agree to them. Contact: <a href="mailto:lz@kjt.lol">lz@kjt.lol</a>.
      </p>

      <h2>Your content</h2>
      <p>
        You keep ownership of what you upload. You give the operator a limited license to store, process, and
        send your content to the service&apos;s providers only as needed to run the service for you. You must
        have the right to upload everything you upload, including consent from anyone recorded where the law
        requires it. Don&apos;t use the service for anything illegal or to harm others.
      </p>

      <h2>AI output</h2>
      <p>
        Transcripts, summaries, and chat answers are generated by AI and can be wrong or incomplete. Check
        anything important yourself. Nothing the service produces is professional advice (legal, medical,
        financial, or otherwise).
      </p>

      <h2>No warranty</h2>
      <p>
        The service is provided as is and as available, with no warranties of any kind. It may go down, lose
        data, or change. Keep your own copies of anything you care about.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent the law allows, the operator is not liable for any indirect, incidental, or
        consequential damages, or for lost data or content, arising from your use of the service. Nothing here
        limits rights or liability that the law does not allow to be limited.
      </p>

      <h2>Indemnity</h2>
      <p>
        To the extent the law permits, you agree to cover the operator for claims arising from content you
        upload or from your breach of these terms.
      </p>

      <h2>Suspension and termination</h2>
      <p>
        The operator may suspend or close accounts that break these terms or put the service at risk, and may
        shut down the service. You can stop using it and delete your account at any time.
      </p>

      <h2>Changes</h2>
      <p>
        These terms may be updated. The date at the top will change, and continuing to use the service means
        you accept the new version.
      </p>
    </div>
  );
}
